apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactprodx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactprodx
  template:
    metadata:
      labels:
        app: reactprodx
    spec:
      containers:
      - name: reactprodx
        image: joelwembo/reactprodx:latest
        imagePullPolicy: Always
        ports:
            - containerPort: 80
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 80
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        resources:
            limits:
              memory: 200Mi
              cpu: 50m
            requests:
              cpu: 100m
              memory: 200Mi  