version: "3.8"
services:
    reactprodx:
        container_name: reactprodx
        image: reactprodxt:latest
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "80:80"
        networks:
            - reactprodx-network    

#Docker Networks
networks:
  reactprodx-network:
    driver: bridge