# React Service
apiVersion: v1
kind: Service
metadata:  
  name: reactprodx
spec:
  externalIPs:
  - 18.141.186.159
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: reactprodx
  type: LoadBalancer
status:
  loadBalancer: {}

---

# React Instance
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactprodx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactprodx
  template:
    metadata:
      labels:
        app: reactprodx
    spec:
      containers:
      - name: reactprodx
        image: joelwembo/reactprodx:latest
        ports:
            - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10


---