apiVersion: v1
kind: Service
metadata:  
  name: reactprodx
spec:
  externalIPs:
  - 139.162.39.79
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: reactprodx
  type: LoadBalancer
status:
  loadBalancer: {}